[pytest]  # Configuration File For Pytest
pythonpath = . # Like Import Modules
testpaths = tests # Look for tests in the tests directory
python_files = test_*.py # run files that start with test_ and end with .py